framework:
  messenger:
    transports:
      update_artists:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

    routing:
      # Route your messages to the transports
      App\Message\Artists\update: update_artists
